name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install flake8 pytest pytest-cov
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: Build coverage file
            run: |
              pytest --cache-clear --cov=app testing/ > pytest-coverage.txt
          - name: Comment coverage
            uses: coroo/pytest-coverage-commentator@v1.0.2
          - name: pytest-coverage-commentator
              uses: coroo/pytest-coverage-commentator@v1.0.2
              with:
                pytest-coverage: pytest-coverage.txt
    - name: docker login
      run: |
       docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag siva7/hack0522:1.0.0
    - name: Push Docker Image
      run: docker push siva7/hack0522:1.0.0
